### ISSUE TITLE
Deploy to EKS

### ISSUE THREAD

**Issue by pedroleaoc** [finos/legend-integration-juju#10]
Follow this tutorial: https://gist.github.com/maoo/bafa2ab159054215bd76c20e6dcb0b67

**Comment by claudiubelu** [comment]
We've deployed to EKS as well, and updated the EKS Deployment guide as well.

Related PRs:

Adds updates to the EKS deployment guide: https://github.com/finos/legend-integration-juju/pull/38
Updates the EKS deployment guide to include information about TLS: https://github.com/finos/legend-integration-juju/pull/39
Updates the EKS deployment guide to use certbot-charm: https://github.com/finos/legend-integration-juju/pull/40
Amend some details on the EKS deployment (TLS): https://github.com/finos/legend-integration-juju/pull/41
Restructure the EKS deployment guide: https://github.com/finos/legend-integration-juju/pull/42
Adds a note regarding Proxy TLS termination: https://github.com/finos/legend-integration-juju/pull/44
