### ISSUE TITLE
Consume Docker image versions using manifest.json published by Legend

### ISSUE THREAD

**Issue by pedroleaoc** [finos/legend-integration-juju#11]
Consume Docker image versions using manifest.json published by Legend (see https://github.com/finos/legend/blob/master/releases/2021-10-18/manifest.json and https://github.com/canonical/charmhub-upload-action

**Comment by claudiubelu** [comment]
This was added to the legend-juju-bundle repo: https://github.com/finos/legend-juju-bundle/pull/9
