### ISSUE TITLE
Legend configuration and versions are up to date

### ISSUE THREAD

**Issue by pedroleaoc** [finos/legend-integration-juju#12]

**Comment by claudiubelu** [comment]
We are now publishing the official FINOS Legend image versions listed in the release's ``manifest.json``: https://github.com/finos/legend-juju-bundle/pull/9

There were a few PRs that were made to update the Legend service configurations:

https://github.com/finos/legend-juju-engine-server-operator/pull/18
https://github.com/finos/legend-juju-studio-operator/pull/13
