### ISSUE TITLE
Tutorial for local run

### ISSUE THREAD

**Issue by pedroleaoc** [finos/legend-integration-juju#13]

**Comment by pedroleaoc** [comment]
https://github.com/finos/legend-integration-juju/commit/dae378d329783c8aff9b823c728108e98f58eed6

**Comment by pedroleaoc** [comment]
Waiting on https://github.com/finos/legend-integration-juju/issues/26

**Comment by claudiubelu** [comment]
We've added / updated the guide for the local run: https://github.com/finos/legend-integration-juju/blob/1de2c7b60289b0ff03a23f5e6a9a57c3e1be6bea/docs/deploy/local.md

Using the local deployment guide yields consistent results.
