### ISSUE TITLE
Tutorial for EKS deployment 

### ISSUE THREAD

**Issue by pedroleaoc** [finos/legend-integration-juju#14]

**Comment by pedroleaoc** [comment]
Waiting on https://github.com/finos/legend-integration-juju/issues/26

**Comment by claudiubelu** [comment]
I've added some instructions here: https://gist.github.com/claudiubelu/d2472fd5846914ab24f7aa83a464bd74
Targeted by: https://github.com/finos/legend-integration-juju/pull/34

**Comment by claudiubelu** [comment]
We've updated the EKS deployment guide. Now it includes quite a bit of useful information, including enabling TLS: https://github.com/finos/legend-integration-juju/blob/1de2c7b60289b0ff03a23f5e6a9a57c3e1be6bea/docs/deploy/aws-eks.md
