### ISSUE TITLE
Automate the updating of releases on charmhub

### ISSUE THREAD

**Issue by pedroleaoc** [finos/legend-integration-juju#16]

**Comment by claudiubelu** [comment]
We've automated the charm and bundle release process. More information about it and how it works can be found here: https://github.com/finos/legend-integration-juju/blob/1de2c7b60289b0ff03a23f5e6a9a57c3e1be6bea/README.md#legend-charm-and-bundle-release-automation-process

Added in: https://github.com/finos/legend-integration-juju/pull/49
