### ISSUE TITLE
The finos-legend-bundle must deploy 3 instances of Nginx

### ISSUE THREAD

**Issue by pedroleaoc** [finos/legend-integration-juju#29]
They all need to have different aliases i.e. juju deploy ngnix <nginx_alias>

**Comment by pedroleaoc** [comment]
finos/legend-juju-bundle#3

**Comment by claudiubelu** [comment]
Fixed by: https://github.com/finos/legend-juju-bundle/pull/3

The PR merged, we can close this now.

**Comment by claudiubelu** [comment]
Also addressed by: https://github.com/finos/legend-juju-bundle/pull/4
