### ISSUE TITLE
The GitLab integrator charm must use the domain name as callback

### ISSUE THREAD

**Issue by pedroleaoc** [finos/legend-integration-juju#30]

**Comment by claudiubelu** [comment]
We've updated the Legend Charms to have an ``external-hostname`` config option, which will be then passed to the gitlab integrator charm for its Redirect URIs. By default, we've set the ``external-hostname`` to ``legend-host`` in the bundle, but any other name could be used, including resolvable FQDNs.

Related PRs:
- https://github.com/finos/legend-juju-libs/pull/8
- https://github.com/finos/legend-juju-engine-server-operator/pull/8
- https://github.com/finos/legend-juju-sdlc-server-operator/pull/9
- https://github.com/finos/legend-juju-studio-operator/pull/7
- https://github.com/finos/legend-juju-libs/pull/11
- https://github.com/finos/legend-juju-engine-server-operator/pull/14
- https://github.com/finos/legend-juju-sdlc-server-operator/pull/14
- https://github.com/finos/legend-juju-studio-operator/pull/11
- https://github.com/finos/legend-juju-bundle/pull/6
