### ISSUE TITLE
Local run with gitlab.com working across the (Canonical/CloudBase/FINOS) team

### ISSUE THREAD

**Issue by pedroleaoc** [finos/legend-integration-juju#8]

**Comment by claudiubelu** [comment]
This is completed, the ``finos-legend-bundle`` can be reliably deployed locally. We've also updated the local deployment guide with new information: https://github.com/finos/legend-integration-juju/blob/1de2c7b60289b0ff03a23f5e6a9a57c3e1be6bea/docs/deploy/local.md
